--product list-expenditures

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'baguette', 'carrefour', null, 0.25, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'baguette', 'boulangerie', null, 0.22, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'baguette', 'lidl', null, 0.25, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'baguette croustille', 'lidl', 1, 0.25, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'baguette cereales', 'lidl', 1, 0.23, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'demi baguette rustiq', 'lidl', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'baguette rustiq', 'lidl', 1, 0.25, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pain special graines', 'lidl', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pain', 'carrefour', null, 0.4, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pain', 'boulangerie', null, 0.4, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'croissant', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'croissant', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'croissant pur beurre', 'lidl', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'mini-viennoiseries croissant', 'lidl', 8, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'mini croissant', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'mini croissant', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'mini croissant', 'viroise express', 8, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'croissant', 'e leclerc', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'farine de ble', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'farine de ble', 'label rouge', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'farine de ble', 'navarre', null, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'farine fluide', 'navarre', null, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'sucre', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'sucre en poudre', 'navarre', null, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'camambert de carac', 'carrefour',null, 0.125,null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'camambert de campaigne', 'president',null, 0.250, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'camambert', 'president',null, 0.250, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'camambert', 'cœur de lion',null, 0.150, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'fromage de brebis', 'lou perac',null, 0.1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'fromage de chevre', 'savencia', null, 0.18, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'fromage fondu a la creme', 'kiri', 8, 0.16, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'fromage blanc fondu', 'milbona', null, 0.24, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'fromage a pate molle', 'mini caprice', null, 50, null, 'gr')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'fromage au lait cru de chevre', 'petit pouligny', null, 150, null, 'gr')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'emmantel rape', 'carrefour', null, 0.2, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'emmantel rape', 'president', null, 0.2, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'bio coulommiers', 'paturage', null, 0.35, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'mozarella', 'casa azzura', null, 0.125, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'confiture framboise', 'maribel', null, 0.45, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'confiture 4fruits', 'maribel', null, 0.45, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'nutella', 'ferrero', null, 0.825, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'nutella', 'ferrero', null, 0.4, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pate a tartiner speculoos', 'lotus', null, 0.4, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pate a tartiner speculoos', 'favorina', null, 0.35, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'miel de fleurs', 'maribel', null, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'miel de fleurs glass', 'maribel', null, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pizza 4 fromages', 'toque du chef', null, 0.470, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pizza crust', 'sodebo', null, 0.580, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'noodle', 'noodlicious', null, 0.065, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'noodle poule aroma', 'noodlicious', null, 0.065, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'noodle', 'banzai', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'yaourt nature', 'carrefour', 12, 1.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'yaourt', 'danone', 4, 0.125, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'yaourt brasse', 'envia', 16, 2, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'yaourt nature', 'envia', 16, 2, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'yaourt fraise', 'yoplait', 4, 0.125, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'perle de lait', 'yoplait', 4, 0.125, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'graines de chanvre', 'activa', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'beurre', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'beurre', 'president', 1, 0.25, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'beurre demi sel', 'envia', 1, 0.25, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'beurre demi sel gastronomique', 'envia', 1, 0.25, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'beurre doux', 'fs', null, 0.250, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'beurre traditionel', 'surgeres', null, 0.250, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'Œuf de poules plein air', 'Carrefour', 12, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'Œuf plein air', 'lidl', 12, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'Œuf frais moyen', 'Carrefour', 20, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'Œuf moyen', 'Carrefour', 20, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'Œuf de poulet', 'Carrefour', 6, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'Œufs au sol', 'carrefour', 10, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'Œufs frais', 'kervenach', 10, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'Œufs frais', 'kervenach', 12, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'Œufs gros crf', 'carrefour bio', 4, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'Œuf de poules plein air','carrefour', 20, null, 1, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'legume vapeur broc carot mais', 'freshona', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'melange de legume mexicaine', 'freshona', 1, 0.75, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pomme banane puree', 'le berger des fruits', 4, 0.1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'mini viennoiserie', 'e leclerc', 15, 0.375, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'boules de cereals', 'pp blanc', null, 0.750, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'muesli', 'carrefour', null, 0.750, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'muesli bio cereal', 'lidl', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'petales de ble', 'carrefour', 1, 0.75, null, 'kg')

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'ketch-up', 'heinz', null, 0.46, 0.4, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'ketch-up', 'heinz', null, 1.5, 1.32, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'mayonnaise', 'ulker', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'mayonnaise', 'saucee', 1, 0.465, 0.5, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'hot sauce', 'saucee', 1, 0.505, 0.5, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'lentil', null, null, 2, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'olive', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'huile vegetale', 'carrefour', null, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'huile vegetale', 'vita dor', null, null, 5, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'huile olive', null, 1, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'huile olive vierge', 'companie extremena', 1, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'huile olive vierge', 'companie extremena', 1, null, 2, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'huile olive vierge', 'companie extremena', 1, null, 3, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'betteraves bio', 'carrefour', null, 0.2, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'la gache', 'la fournee doree', null, null, null, null)
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'legumes du soleil, semoule, poulet', 'nestle naturnes', 2, 0.19, null, null)
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'carottes', 'nestle naturnes', 2, 0.13, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'mais extra doux', 'freshona', null, 0.285, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'riz long grain', 'uncle bens', null, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'riz long grain', 'comptoir du grain', null, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pates', 'macaroni', null, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'gnocchi avec pommes de terre', 'rana', null, 0.3, null, null)
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'creps de bretagne', 'galettes bertel', 4, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'galettes cereals', 'cereal bio', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'haricot lingot', null, null, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'levure boulangere', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'olives vertes', 'saladinettes', 1, null, null, 'kg')


insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'batonnets poisson','ocean sea', 30, 0.9, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'batonnets panes colin alaska','ocean sea', 30, 0.9, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'batonnets poisson',null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'filets de saumon', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'colin alaska', 1, 0.8, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'filet de colin alaska', 'ocean sea', 0.95, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'saumon', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'paves de saumon', null, 4, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'2 paves de saumon', 'ASC', 2, 0.28, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'viande hache', 'supérette flérienne', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'bifteck', 'supérette flérienne', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'cuisse de poulet', 'supérette flérienne', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'saucisse', 'ozyorem', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'salami', 'ozyorem', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'salade de legumes, poisson et boulgour','petit pierre', null, 0.25, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'ravioli saumon', 'William Saurin', null, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'ravioli saumon', 'William Saurin', null, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'saumon', null, null, 1, null, 'kg')

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'sel fin', 'cerebos', null, 0.125, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'sel fin verseuse', 'chantefin', null, 0.75, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'poivre noir moulu', 'kania', null, 0.044, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'herbes provence', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'origan', 'kania', null, 0.012, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'clous girofle', 'ducros', null, 0.023, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'curcuma moulu', 'kania', null, 0.040, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'gingembre moulu', 'ducros', null, 0.026, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'cannelle', 'ducros', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'curry', 'kania', null, 0.046, null, 'kg')

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'orange', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'orange declasse', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'orange', null, null, 3, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'orange navelina', null, null, 3, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'orange a jus', null, null, 1.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pomme', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pomme', 'breburn', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pomme golden', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pomme golden', null, null, 2, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'poire', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'banane', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'banane', 'darier', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'bananes cavendish', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'banane bio fairtrade', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tomate', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tomate ronde', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tomate ronde grappe', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tomate allongees', 'saveol', null, 0.6, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'clamentine', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'clamentine corse', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'clamentine feuille', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'clamentine oronule', 'exportaciones s aranda', null, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'clamentine clemenules', null, null, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'clamentine berkane', null, null, null, null, 'kg')

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'citron', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'citron filet', null, null, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'citron bio', 'mamarica', null, 0.4, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'citron primofiori', 'lapaz', 1, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'citron primofiori', 'garcia', 1, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'citron primofiori', 'tyler', 1, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'citron primofiori', 'rosegar', 1, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'avocat', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'cerise', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'fraise', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'raisin', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'raisin blanc', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'peche', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'melon', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'ananas', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'kiwi', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'figue caque', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'grenade', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'myrtille', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'myrtille', 'driscoll', 1, 0.125, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'framboise', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'framboise', 'driscolls', null, null, null, 'kg')

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pomme de terre', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pomme de terre europe', 'sas paul marc', 1, 5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pomme de terre europe', 'sas paul marc', 1, 10, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pomme de terre amandine', 'princesse', 1, 1.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'pomme de terre grenailles', 'cote marche', 1, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'oignon', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'oignon jaune', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'oignon jaune', 'cote marche', 1, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'oignon blanc', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'epinard', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'celeri rave', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'poireaux', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'chou bruxelles', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'chou brocoli', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'mais', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tomate', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tomate cerise', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'concombre', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'concombre', 'unica fresh', null, 0.25, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'carotte', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'carotte', 'conso', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'carotte', 'primeale', null, 2, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'carotte', 'gosselin', null, 2, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'ail', 'violet', null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'courge', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'chou fleur', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'aubergine', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'artichout', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'poivron', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'poivron jaune', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'poivron mix', null, 3, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'paprika mix', 'hortalizas', 3, 0.5, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'asperge', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'bette', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'betterave', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'radis', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'navet', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'navet rave', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'brocoli', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'celeri', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'champignon', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'chayote', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'endive', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'haricot', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'haricot coco', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'haricot coco fonce', 'provence vivarais', null, 0.4, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'chou', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'laitue', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'laitue', 'batavia blond', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'menthe', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'persil', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'basilic', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'salade iceberg', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'coriandre', null, null, null, null, 'piece')


insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'noix fraiche', null, null, null, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'noix', 'grenoble', 1, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'goûter melanges cranberry', 'alesto', 5, 0.2, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'goûter melanges mix choco', 'alesto', 5, 0.2, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'cranberries sechee', 'alesto', 1, 0.2, null, 'kg')

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'madeleines coquilles', 'sondey', 16, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'petite gâteau', 'madeleines coquilles M', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'chocolat lait eclats', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tartelettes choco-caramel', 'sondey', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tartelettes citron', 'sondey', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'petit beurre choco', 'sondey', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'barni choco', 'mondolez', 5, 0.150, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'lu petit ecolier biscuit', 'mondolez', null, 0.150, null, 'gram')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'lu petit ecolier biscuit', 'mondolez', null, 0.250, null, 'gram')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tablette', 'carrefour', null, 0.14, null, 'gram')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'kinder surprise chocolat', 'kinder', 3, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'lol surprise chocolat', 'zaini', 3, 20, null, 'gr')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'kinder bueno', 'kinder', 6, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'kinder schokobons', 'kinder', null, 0.2, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'kinder country', 'kinder', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'ferrero kinder chocolat', 'kinder', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'biscuit', 'nutella', null, 0.304, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'brownie', 'franprix', null, 0.285, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'biscuits carres', 'monoprix gourmet', null, 0.125, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'biscuits vitalite', 'sondey', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'biscuits', 'oreo', 2, 0.492, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'crepes dentelles', 'casino bio', null, 0.085, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'gateau', 'marbre', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'chocolat', 'snickers', 5, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'chocolat', 'milkway', 14, 0.227, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'chocolat', 'toblerone', 0.1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'chocolat lait eclats', 'fin carre', 3, 0.1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tarte pommes', 'eleclerc', 1, 0.87, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'tzatziki', 'marque repere', 1, 0.2, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (1,'ktiriti', 'marque repere', 1, 0.2, null, 'kg')


insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'eau mineral', 'badoit', null, null, 1, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'eau mineral', 'perrier', null, null, 1, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'lait', 'candia', null, null, 1, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'lait', 'lactel', null, null, 1, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'lait fraiche', null, 1, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'lait baby croissance', 'candia', 1, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'thé', 'filiz', null, 1, null, 'kg')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'thé noir', 'lord nelson', 20, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'thé ceylan', 'lord nelson', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'thé early grey', 'lord nelson', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'thé english breakfast', 'carrefour', 25, 50, null, 'gram')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'thé earl grey', 'twinings', 25, 50, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'ice tea', 'lipton', null, 1, null, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'ice tea citron vert', 'lipton', null, null, 1.5, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'eau mineral naturelle', 'bar le duc', 1, null, 0.5, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'cola', 'pepsi', 1, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'cola', 'coca cola', 1, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'cappucino', 'viroise express', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (2,'cafe allonge', 'viroise express', 1, null, null, 'piece')

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'essuie-tout 3 plis', 'floralys', 204, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'essuie-tout maxi rouleau', 'Floralys', 350, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'couche', 'lupidu', 44, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'lingettes bebes', 'lupidu',null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'lingettes comfort', 'lupidu', 100, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'lingettes', 'huggies', 56, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'eponges vegetales', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'liquid vaisselle', 'w5', null, null, 0.5, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'liquid vaisselle', 'w5', null, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'liquid vaisselle citron', 'mir', null, null, 0.75, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'lessive liquide', 'henkel', null, null, 3, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'détergent à lessive liquide', 'ariel', null, null, 1.815, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'mouchoirs blancs', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'papier toilette', 'floralys', 12, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'papier toilette', 'floralys', 20, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'always ultra', null, 26, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'brosse dent', 'signal', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'dentifrice anti tartre', 'signal', 1, null, 75, 'mililiter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'sac poubelle', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'sac poubelle 5 lt', 'dumil', 30, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'sac caisse papier', 'carrefour', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'sac en papier', 'lidl', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'freeze bag 24x32', 'dumil', 75, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'savon olive', 'cien', null, null, 1.25, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'savon liquide', 'cien', null, null, 0.5, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'savon liquide amande', 'cien', null, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'shampoo', 'head&shoulders', null, null, 0.28, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3,'dentifrice', 'signal', null, null, 75, 'mililiter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'gel douche coconut','cien', null, null, 1, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'gel douche melon','cien', null, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'lotion hydrante lait damande','cien', null, null, 0.3, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'gel raser','cien', null, null, 0.2, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'creme hydratante','dove', null, null, 0.2, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'mouchoir blancs','floralys', 60, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'spray nettoyant',null, null, null, null, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'rasoir jetable',null, 3, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'gel douche', 'cadum', null, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'adoucisseur', 'silan', 1, null, 0.9, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'adoucisseur', 'cojoline', 1, null, 1.16, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'nettoyant menager salle de bain', 'ajax', 1, null, 0.75, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'gel wc javel', 'w5', 1, null, 1, 'liter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'serviettes', 'always', 26, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'deboucheur poudre', 'tarax', 1, 60, null, 'gram')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (3, 'deboucheur gel', 'destop', 1, null, 500, 'mililiter')

select * from product
where proBrand like '%alw%'


insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'chemise fille', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'slip garçon', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'slip fille', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'veste enfant', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'robe', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'parka', 'jack&jones', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'chausures', 'nike air max', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'botte fille', 'FPC', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'parka fille', 'Charlie Prune', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'sous pull', 'Charlie Prune', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'jupe fille', 'Charlie Prune', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'pantouf', null, 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'jammer', 'technopro', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'sac de sport', 'nike', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'slipper', 'technopro', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'bonnet', 'jack&jones', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'bonnet de natation', 'its', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'swimsuit', 'arena', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'sweat rouge 3 ans', 'gemo', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'tee-shirt jaune 3 ans', 'gemo', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (4,'tee-shirt bleu 3 ans', 'gemo', 1, null, null, 'piece')


insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (5, 'charger mural', 'linkster', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (5, 'ampul halogene 28 watt', 'dimmable', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (5, 'ampul led 3 watt 250 lumen', 'livarnolux', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (5, 'pil, 1.5 V zinc carbon aa','panasonic', 12, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (5, 'pil, 1.5 V zinc carbon aaa','panasonic', 12, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (5, 'cell phone','redmi note 9', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (5, 'montre', 'intersport', 1, null, null, 'piece')



insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'guirlande wit', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'ballons',null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'ruban adhesif', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'ciseaux grijs', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'papier cadeau', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'collant enfant', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'sac cadeau', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'accesoir cheveux', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'elastiques spirale dans balle', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'clic-clacs', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'set brosses cheveux', null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'etui a crayon', 'dlp industry', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6, 'tasse',null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6, 'livre 24x32 96 pages','harmelin', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6, 'livre 17x22 96 pages','oxford', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6, 'feutres','bic', 10, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6, 'feutres de couleur','bic', 12, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6, 'print','bison', 2, 21, null, 'gram')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6, null,'amazon', 1, null, null, null)
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'backpack', 'nike', null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'ruban adhesif', 'washi', 3, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'trousse avec paillettes', null, 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (6,'baton de colle', 'bison', 2, 21, null, 'gr')



insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (7,'course python&machine learning', 'udemy', 1, null, null, 'piece')


insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (9, 'canards en plastique',null, null, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (9, 'patins en feutre','crelando', 32, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (9, 'aiguilles a coudre','crelando', 80, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (9, 'fil universe','crelando', 8, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (9, 'trousse beau',null, 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (9, 'pate a modeler','creative kids', 5, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (9, 'action poly','cabas', 1, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (9, 'puzzel 24 pieces',null, 1, null, null, 'piece')

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (10, 'gel desinfectant', 'kapa-reynolds', 1, null, 75, 'mililiter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (10, 'hand gel', 'sanicur', 1, null, 50, 'mililiter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (10, 'masque protection', 'chiara ambra', 10, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (10, 'doliprane', null, null, 500, null, 'miligram')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (10, 'masque jetables 3 couches', null, 10, null, null, 'piece')



insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (11, 'baume a levres', 'cien', null, 4.8, null, 'gram')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (11, 'vernis à ongle', 'cien', null, null, 10, 'mililiter')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (11, 'hydratant matifiant','henkel france', null, null, 0.05, 'liter')

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (13, 'ligne telephone','reglo', null, null, null, 'mois')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (13, 'abonnment','netflix', null, null, null, 'mois')

insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (14, 'tasse de the','pasabahce', 6, null, null, 'piece')
insert into product (catId, proName, proBrand, proQty, proWght, proVol, proType)values (14, 'tasse de eau','doro', 6, null, null, 'piece')

select * from category